### ISSUE TITLE
add installation instruction on Readme

### ISSUE THREAD

**Issue by hozefaj** [PolymerElements/paper-tooltip#118]
### Description
Would be good to have installation instructions available on Readme. Plus move away from using `bower` and just use `npm`

### Expected outcome
1. Replace `bower` with `npm` and `yarn` as this where the whole front end community is moving.
2. Also would be good to have installation instructions on the Readme.

### Actual outcome
Readme is updated with installation instructions.

**Comment by notwaldorf** [comment]
Thanks! Unfortunately, before we can do this, there needs to be a much bigger change wrt Polymer. Because of how HTML Imports work, you _need_ a flat install, and if you just published the element as it is on npm, it wouldn't work.

Please keep an eye on https://github.com/Polymer/polymer/issues/326 for an updated status!

**Comment by hozefaj** [comment]
Thanks for the info
