### ISSUE TITLE
Uses Deprecated neon-animation

### ISSUE THREAD

**Issue by homerjonathan** [PolymerElements/paper-tooltip#121]
### Description

Uses the neon-animation component which shows at https://www.webcomponents.org/element/PolymerElements/neon-animation to be deprecated.

Neon-animation component page recommends that we use web animations API or CSS animations as a replacement.

Pulling the neon-annimation library is a very large load for simply allowing the tooltip to fade in and out.   Would this be in the development plan? Which direction will this component be going in?

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by xelra** [comment]
While using `gold-password-input` I noticed that I got warnings about neon-animation. https://github.com/GeoloeG/gold-password-input/issues/32#issuecomment-349941539

This requires a polyfill now.
```
<script src="bower_components/web-animations-js/web-animations-next-lite.min.js"></script>
```

> ⚠️ This Element is now deprecated ⚠️
Please use the web animations api or CSS animations
Web animations polyfill is now a dev dependency

Before rewriting paper-tooltip to use the web animations api, could we have it load the polyfill in the meantime? Because in its current state paper-tooltip is broken.

**Comment by notwaldorf** [comment]
@e111077 you are our animations expert, pls halp :)

**Comment by e111077** [comment]
These elements will eventually be migrated to no longer include neon animations.

Progress on this is delayed as this takes a large amount of effort as there are many elements that rely on neon animations and many users that rely on the neon animation api.

**Comment by xelra** [comment]
@e111077 Can we have paper-tooltip load the polyfill in the meantime to temporarily keep it working until the migration is done?

That would keep paper-tooltip working without everyone fixing it themselves.
