### ISSUE TITLE
paper-tooltip is sensitive to overflow+position

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/paper-tooltip#15]
when you have a div, which has ```overflow: hidden;``` and then somewhere in another div with ```position: relative;``` the paper-tooltip will not be shown.
A snippet below:
```
<div style="overflow: hidden;">
	<div style="position: relative;">
		<div style="display:inline-block">
		  <button>Click me!</button>
		  <paper-tooltip>I will not be shown!</paper-tooltip>
		</div>
	</div>
</div>
```

**Comment by notwaldorf** [comment]
So there's a couple of things here, some that make sense:
- `overflow: hidden` means that anything outside the div will be clipped out. Since the `position:relative` div will be sized to its button child (the only one with a relative position), the tooltip is drawn outside is rect, and will be clipped. If you add a `height: 100px` to it, it will be shown.

What's interesting is that the tooltip is only shown after you click on the button, so when it becomes focused, as if the `mouseover` event isn't triggered. I'll take a look at that.

**Comment by eximius313** [comment]
So why previous core-tooltip worked just fine with this settings?
This is a tooltip - something that should always show and it shouldn't be interfered by other elements.

**Comment by notwaldorf** [comment]
@eximius313 `core-tooltip` was a completely different element: it wrapped the thing that it was tooltip-ing. This is not a great approach -- on one hand because in the shadow dom, your element will completely disappear, and on the other hand that (ideologically) a tooltip is something that attaches to something, not wraps something else.

**Comment by eximius313** [comment]
So - ideologically - should tooltip not show up because some parent elements influence it, or it should always pop up when mouse is hover on the element it's attached to?

**Comment by notwaldorf** [comment]
It _should_ always pop up when the element it's attached to (this is either the parent, or th element specified in the `for` attribute). The problem is that it still subject to CSS rules: if the parent has `overflow: hidden`, the tooltip is showing up, but the parent will not show it unless it has enough space to show it.

**Comment by reinert** [comment]
It's really a shame that a tooltip is susceptible to being hidden. :disappointed:
