### ISSUE TITLE
Button or Link in tooltip

### ISSUE THREAD

**Issue by StokeMasterJack** [PolymerElements/paper-tooltip#67]
I would like to be able to put a button or a link in a tool tip. Gmail does this. When you hover over the sender's name a tooltip pops up. But you can actually _interact_ with that tooltip, by clicking "Add to Circles" for example.

This functionality requires the tooltip to _not_ disappear when you move your pointer _over_ the tooltip.

Thanks.

**Comment by notwaldorf** [comment]
I think it's unlikely we would add this feature to the tooltip -- it's current implementation is based on the material design [spec](https://material.google.com/components/tooltips.html) which is pretty opinionated and discourages the use of rich content in the tooltip. Moreover, there's explicit code to hide the tooltip as soon as you hover over it, so that it doesn't linger for too long.

The workaround is probably for you to make your own element, losely based on `paper-tooltip`, that meets your requirements. :(
