### ISSUE TITLE
Passing content breaks paper-tooltip under shadow dom

### ISSUE THREAD

**Issue by kevin-wise-infusionsoft** [PolymerElements/paper-tooltip#68]
### Description

Passing only `<content></content>` to `paper-tooltip` causes it to fail when running in shadow DOM.
### Expected outcome

The tooltip is displayed when it should be (mouseover, etc).
### Actual outcome

The tooltip is never displayed since the condition `Polymer.dom(this).textContent.trim() === ''` is not true in shadow DOM.
### Live Demo

https://jsbin.com/serepemaye/edit?html,output
Note this works:
https://output.jsbin.com/serepemaye?dom=shady
This does not:
https://output.jsbin.com/serepemaye?dom=shadow
### Steps to reproduce
1. Create a component that passes only `<content></content>` to `paper-tooltip` 
2. Add this component to a page, with text or html that should get passed to paper-tooltip via the content tag.
3. Run with shadow dom (`?dom=shadow`)
### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [Unconfirmed] Safari 9
- [Unconfirmed] Safari 8
- [Unconfirmed] Safari 7
- [Unconfirmed] Edge
- [ ] IE 11
- [Unconfirmed] IE 10

**Comment by kevin-wise-infusionsoft** [comment]
There is a workaround: include a hidden element containing text content in addition to the `<content></content>`.  For example: `<paper-tooltip><span hidden>X</span><content></content></paper-tooltip>`.

**Comment by notwaldorf** [comment]
I think we explicitly tried to not show a tooltip if it doesn't have any content -- because that doesn't exactly make sense. Why are you trying to show an empty tooltip in the first place?

I don't see a difference in the shadow or shady DOM in the jsbins provided. In both of them, the tooltip doesn't show up at all when the target is hovered over.

**Comment by brogers4** [comment]
I have seen this issue as well.  I attempted to write a very simple element that extended paper-tooltip and used the `<content>` tag.  I am not trying to show a tooltip without content, but paper-tooltip thinks that the content is empty.

Here is the very simple element I tried to create which exhibits the same issue as described above:
```
<dom-module id="my-helper-tooltip">
  <template>
    <iron-icon id="helperIcon" icon="icons:help-outline"></iron-icon>
    <paper-tooltip id="helperTooltip" for="helperIcon" position="{{position}}">
      <content></content>
    </paper-tooltip>
  </template>
  <script>
    Polymer({
      is: 'my-helper-tooltip',

      properties: {
        position: {
          type: String,
          value: "right"
        }
      }
    })
  </script>
</dom-module>
```

I looked at the code, and the problem is in [this line of code](https://github.com/PolymerElements/paper-tooltip/blob/master/paper-tooltip.html#L261):

```
if (Polymer.dom(this).textContent.trim() === '')
    return;
```

The `textContent` property does not resolve the effective children within the `<content>` tag.  I modified the above code to the following and it worked:

```
var empty = true;
var effectiveChildren = Polymer.dom(this).getEffectiveChildNodes();
for(var i=0; i<effectiveChildren.length; i++){
  if(effectiveChildren[i].textContent.trim() !== ''){
    empty = false;
    break;
  }
}
if(empty) return;
```

This allows you to look at the effective children while still not showing when it is empty.
