### ISSUE TITLE
How to clone tool-tip element?

### ISSUE THREAD

**Issue by xliiv** [PolymerElements/paper-tooltip#74]
I'd like to clone div including `tool-tip` to other element.
See live demo.
I'd expect that cloned element also has tooltip (but it doesn't).

### Live Demo

http://jsbin.com/vololicezu/1/edit?html,output

### Browsers Affected

- [ x] Chrome
- [ ] Firefox ?
- [ ] Safari 9 ?
- [ ] Safari 8 ?
- [ ] Safari 7 ?
- [ ] Edge ?
- [ ] IE 11 ?
- [ ] IE 10 ?

**Comment by notwaldorf** [comment]
The cloning part works fine -- if you look at the resulting DOM, the tooltip is in the right place:
<img width="262" alt="screen shot 2016-05-31 at 10 43 45 am" src="https://cloud.githubusercontent.com/assets/1369170/15684585/917ef5c4-271c-11e6-989e-42c28a2e5377.png">

The problem is that because you did a literal clone, and the tooltip targets a specific element (`for="id_1"`):, your cloned tooltip still targets the first span, so you'll have to update the IDs with something like:
```
var newPlace = document.querySelector('#new-place');
newPlace.querySelector('span').id = 'id_2';
newPlace.querySelector('paper-tooltip').for = 'id_2';
```

Here's your jsbin, updated with this code: http://jsbin.com/sitawo/edit?html,output

**Comment by xliiv** [comment]
Thanks for clarification. :)
Of course tooltip can be used without ids, like documentation says
https://elements.polymer-project.org/elements/paper-tooltip?view=demo:demo/index.html
section:
"Tooltips can be anchored to elements relative to their parent"
